version: "3"
services:
  node-app:
    build: ./nodeapp
    ports:
      - "300:3000"
    environment:
      - PORT=3000
      - MONGO_USER=simon
      - MONGO_PASSWORD=motdepasse
    depends_on:
      - mongodatabase
    
  mongodatabase:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=simon
      - MONGO_INITDB_ROOT_PASSWORD=motdepasse
      - MONGO_USER=simon
      - MONGO_PASSWORD=motdepasse

    volumes:
      - mongo-database-volume:/data/db

volumes:
  mongo-database-volume: