version: "3"
services:
  nginx: 
    image: nginx:1.13.8-alpine
    ports:
      - "3000:80"
    depends_on:
      - mongodatabase
      - node-app
      - rediscontainer
      - compteurdevote
      - makefile
      - memo
      - waiting

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      
  node-app:
    build: ./nodeapp
    environment:
      - PORT=3000
      - MONGO_USER=simon
      - MONGO_PASSWORD=motdepasse
    depends_on:
      - mongodatabase
    
  mongodatabase:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=simon
      - MONGO_INITDB_ROOT_PASSWORD=motdepasse
      - MONGO_USER=simon
      - MONGO_PASSWORD=motdepasse
      - SECRET_SESSION=ceciestunsecret
    volumes:
      - mongo-database-volume:/data/db

  rediscontainer:
    image: redis:5.0

  compteurdevote:
    build: ./compteurDeVote
  
  makefile:
    build: ./makefile

  memo:
    build: ./memo

  waiting:
    build: ./waiting

volumes:
  mongo-database-volume: